import type { CategoryKey, ImageKey, Product, Tone } from "./types";

// Products, prices, specs and lab values are placeholders until confirmed by the shop (see README).

export const CATEGORIES: { key: CategoryKey; image: ImageKey; tone: Tone }[] = [
  { key: "flowers", image: "jar", tone: "kraft" },
  { key: "oils", image: "bottle", tone: "sage" },
  { key: "cosmetics", image: "tin", tone: "subtle" },
  { key: "accessories", image: "grinder", tone: "sageStrong" },
];

export const PRODUCTS: Product[] = [
  {
    id: "aromaoel-10",
    category: "oils",
    image: "bottle",
    tone: "sage",
    price: 39.9,
    shipping: true,
    badge: "bestseller",
    coa: { batch: "CP-2410", cbd: 10.2, cbg: 0.4, thc: 0.18, tested: "2026-09" },
    de: {
      slug: "cbd-aromaoel-10",
      name: "CBD Aromaöl 10 %",
      meta: "CBD Öl · 10 ml",
      short: "Unser meistgefragtes CBD Öl: 1.000 mg CBD in 10 ml Hanfsamenöl – laborgeprüft, mit Analysezertifikat zur aktuellen Charge.",
      description: [
        "Das CBD Aromaöl 10 % ist der Klassiker in unserem Sortiment und das Öl, nach dem im Shop in der Josefstadt am häufigsten gefragt wird. In 10 ml stecken 1.000 mg CBD, gelöst in Hanfsamenöl. Die Pipette im Verschluss macht das Dosieren einfach und sauber.",
        "Wie alle CBD-Öle wird es in Österreich als Aromaöl verkauft und ist laut Kennzeichnung nicht zum Verzehr bestimmt. Der THC-Gehalt liegt unter dem gesetzlichen Grenzwert von 0,3 % – das bestätigt das Analysezertifikat eines unabhängigen Labors, das es zu jeder Charge gibt.",
        "Du überlegst, ob 5 %, 10 % oder 20 % besser zu dir passt? Komm in der Josefstädter Straße 56 vorbei oder ruf uns an – wir erklären dir die Unterschiede ehrlich und ohne Verkaufsdruck.",
      ],
      specs: [
        ["CBD-Gehalt", "10 % (1.000 mg pro Flasche)"],
        ["Inhalt", "10 ml, Glasflasche mit Pipette"],
        ["Trägeröl", "Hanfsamenöl"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Produktart", "Aromaöl – nicht zum Verzehr bestimmt"],
        ["Laborbericht", "Charge CP-2410"],
      ],
    },
    en: {
      slug: "cbd-aroma-oil-10",
      name: "CBD Aroma Oil 10%",
      meta: "CBD oil · 10 ml",
      short: "Our most requested CBD oil: 1,000 mg CBD in 10 ml hemp seed oil — lab-tested, with a certificate of analysis for the current batch.",
      description: [
        "The CBD Aroma Oil 10% is the classic in our range and the oil customers ask for most often in our Josefstadt store. Each 10 ml bottle contains 1,000 mg CBD dissolved in hemp seed oil, and the dropper cap keeps handling simple and clean.",
        "Like all CBD oils in Austria, it is sold as an aroma oil and labelled as not intended for consumption. Its THC content is below the legal limit of 0.3% — confirmed by a certificate of analysis from an independent lab for every batch.",
        "Not sure whether 5%, 10% or 20% suits you best? Visit us at Josefstädter Straße 56 or give us a call — we’ll explain the differences honestly and without any sales pressure.",
      ],
      specs: [
        ["CBD content", "10% (1,000 mg per bottle)"],
        ["Volume", "10 ml glass bottle with dropper"],
        ["Carrier oil", "Hemp seed oil"],
        ["THC content", "below 0.3%"],
        ["Product type", "Aroma oil — not for consumption"],
        ["Lab report", "Batch CP-2410"],
      ],
    },
  },
  {
    id: "aromaoel-5",
    category: "oils",
    image: "bottle-5",
    tone: "subtle",
    price: 24.9,
    shipping: true,
    coa: { batch: "CP-2408", cbd: 5.1, cbg: 0.2, thc: 0.12, tested: "2026-08" },
    de: {
      slug: "cbd-aromaoel-5",
      name: "CBD Aromaöl 5 %",
      meta: "CBD Öl · 10 ml",
      short: "Der sanfte Einstieg: 500 mg CBD in 10 ml Hanfsamenöl – laborgeprüft und mit Zertifikat.",
      description: [
        "Das CBD Aromaöl 5 % ist unser Einstiegsöl für alle, die CBD kennenlernen möchten. Eine Flasche mit 10 ml enthält 500 mg CBD in Hanfsamenöl – mild im Aroma und einfach in der Handhabung dank Pipette.",
        "Es wird als Aromaöl verkauft und ist laut Kennzeichnung nicht zum Verzehr bestimmt. Der THC-Gehalt liegt unter 0,3 %; das Analysezertifikat der aktuellen Charge zeigen wir dir gerne.",
        "Im Shop in der Josefstädter Straße 56 beraten wir dich persönlich, welche Konzentration zu dir passt.",
      ],
      specs: [
        ["CBD-Gehalt", "5 % (500 mg pro Flasche)"],
        ["Inhalt", "10 ml, Glasflasche mit Pipette"],
        ["Trägeröl", "Hanfsamenöl"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Produktart", "Aromaöl – nicht zum Verzehr bestimmt"],
        ["Laborbericht", "Charge CP-2408"],
      ],
    },
    en: {
      slug: "cbd-aroma-oil-5",
      name: "CBD Aroma Oil 5%",
      meta: "CBD oil · 10 ml",
      short: "The gentle start: 500 mg CBD in 10 ml hemp seed oil — lab-tested and certified.",
      description: [
        "The CBD Aroma Oil 5% is our entry-level oil for anyone getting to know CBD. A 10 ml bottle contains 500 mg CBD in hemp seed oil — mild in aroma and easy to handle thanks to the dropper.",
        "It is sold as an aroma oil and labelled as not intended for consumption. THC content is below 0.3%, and we’re happy to show you the certificate of analysis for the current batch.",
        "In our store at Josefstädter Straße 56 we’ll help you find the concentration that suits you.",
      ],
      specs: [
        ["CBD content", "5% (500 mg per bottle)"],
        ["Volume", "10 ml glass bottle with dropper"],
        ["Carrier oil", "Hemp seed oil"],
        ["THC content", "below 0.3%"],
        ["Product type", "Aroma oil — not for consumption"],
        ["Lab report", "Batch CP-2408"],
      ],
    },
  },
  {
    id: "aromaoel-20",
    category: "oils",
    image: "bottle-20",
    tone: "sageStrong",
    price: 69.9,
    shipping: true,
    coa: { batch: "CP-2409", cbd: 20.3, cbg: 0.8, thc: 0.21, tested: "2026-09" },
    de: {
      slug: "cbd-aromaoel-20",
      name: "CBD Aromaöl 20 %",
      meta: "CBD Öl · 10 ml",
      short: "Hochkonzentriert: 2.000 mg CBD in 10 ml – für alle, die CBD bereits gut kennen.",
      description: [
        "Das CBD Aromaöl 20 % ist unser stärkstes Öl: 2.000 mg CBD in 10 ml Hanfsamenöl. Wer bereits Erfahrung mit CBD hat, schätzt die hohe Konzentration und die lange Reichweite einer Flasche.",
        "Auch dieses Öl wird als Aromaöl verkauft und ist nicht zum Verzehr bestimmt. Jede Charge wird von einem unabhängigen Labor auf Cannabinoide, Pestizide und Schwermetalle geprüft – der THC-Gehalt liegt unter 0,3 %.",
        "Unsicher, ob du die höhere Konzentration brauchst? Wir nehmen uns im Shop gerne Zeit für dich.",
      ],
      specs: [
        ["CBD-Gehalt", "20 % (2.000 mg pro Flasche)"],
        ["Inhalt", "10 ml, Glasflasche mit Pipette"],
        ["Trägeröl", "Hanfsamenöl"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Produktart", "Aromaöl – nicht zum Verzehr bestimmt"],
        ["Laborbericht", "Charge CP-2409"],
      ],
    },
    en: {
      slug: "cbd-aroma-oil-20",
      name: "CBD Aroma Oil 20%",
      meta: "CBD oil · 10 ml",
      short: "Highly concentrated: 2,000 mg CBD in 10 ml — for anyone who already knows CBD well.",
      description: [
        "The CBD Aroma Oil 20% is our strongest oil: 2,000 mg CBD in 10 ml hemp seed oil. Experienced CBD users appreciate the high concentration and how long a single bottle lasts.",
        "This oil is also sold as an aroma oil and is not intended for consumption. Every batch is tested by an independent lab for cannabinoids, pesticides and heavy metals — THC content is below 0.3%.",
        "Not sure whether you need the higher concentration? We’re happy to take our time with you in store.",
      ],
      specs: [
        ["CBD content", "20% (2,000 mg per bottle)"],
        ["Volume", "10 ml glass bottle with dropper"],
        ["Carrier oil", "Hemp seed oil"],
        ["THC content", "below 0.3%"],
        ["Product type", "Aroma oil — not for consumption"],
        ["Lab report", "Batch CP-2409"],
      ],
    },
  },
  {
    id: "lemon-haze",
    category: "flowers",
    image: "jar",
    tone: "kraft",
    price: 34.9,
    shipping: false,
    badge: "new",
    coa: { batch: "CB-2409-LH", cbd: 14.8, cbg: 0.6, thc: 0.24, tested: "2026-09" },
    de: {
      slug: "lemon-haze",
      name: "Lemon Haze",
      meta: "CBD Blüten · 5 g",
      short: "Frisches, zitroniges Aroma, THC unter 0,3 % – erhältlich nur im Geschäft in der Josefstadt.",
      description: [
        "Lemon Haze steht für ein frisches, zitroniges Aroma mit leicht süßer Note. Die Blüten der aktuellen Charge enthalten laut Laborbericht rund 15 % CBD bei einem THC-Gehalt unter 0,3 %.",
        "Hanfblüten fallen in Österreich seit 2025 unter das Tabakmonopol. Wir verkaufen Lemon Haze deshalb ausschließlich in unserem Geschäft in der Josefstädter Straße 56 – ein Versand ist nicht erlaubt. Die Abgabe erfolgt nur an Personen ab 18 Jahren.",
      ],
      specs: [
        ["Inhalt", "5 g"],
        ["CBD-Gehalt", "ca. 15 % (laut Laborbericht)"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Aroma", "Zitrone, frisch, leicht süß"],
        ["Erhältlich", "nur im Geschäft – kein Versand"],
        ["Laborbericht", "Charge CB-2409-LH"],
      ],
    },
    en: {
      slug: "lemon-haze",
      name: "Lemon Haze",
      meta: "CBD flowers · 5 g",
      short: "Fresh, lemony aroma, THC below 0.3% — available only in our Josefstadt store.",
      description: [
        "Lemon Haze stands for a fresh, lemony aroma with a slightly sweet note. According to the lab report, flowers from the current batch contain around 15% CBD with THC below 0.3%.",
        "Since 2025, hemp flowers in Austria fall under the tobacco monopoly. That’s why we sell Lemon Haze exclusively in our store at Josefstädter Straße 56 — shipping is not permitted. Sale to persons aged 18 and over only.",
      ],
      specs: [
        ["Quantity", "5 g"],
        ["CBD content", "approx. 15% (per lab report)"],
        ["THC content", "below 0.3%"],
        ["Aroma", "Lemon, fresh, slightly sweet"],
        ["Availability", "In store only — no shipping"],
        ["Lab report", "Batch CB-2409-LH"],
      ],
    },
  },
  {
    id: "orange-bud",
    category: "flowers",
    image: "jar-orange-bud",
    tone: "sage",
    price: 29.9,
    shipping: false,
    coa: { batch: "CB-2408-OB", cbd: 12.6, cbg: 0.4, thc: 0.21, tested: "2026-08" },
    de: {
      slug: "orange-bud",
      name: "Orange Bud",
      meta: "CBD Blüten · 5 g",
      short: "Fruchtig-süßes Aroma nach Orange, THC unter 0,3 % – erhältlich nur im Geschäft.",
      description: [
        "Orange Bud überzeugt mit einem fruchtig-süßen Duft, der an reife Orangen erinnert. Laut Laborbericht der aktuellen Charge liegt der CBD-Gehalt bei rund 13 %, der THC-Gehalt unter 0,3 %.",
        "Wie alle Hanfblüten gibt es Orange Bud nur bei uns im Geschäft in der Josefstädter Straße 56 und nur für Personen ab 18 Jahren – ein Versand ist gesetzlich nicht erlaubt.",
      ],
      specs: [
        ["Inhalt", "5 g"],
        ["CBD-Gehalt", "ca. 13 % (laut Laborbericht)"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Aroma", "Orange, fruchtig-süß"],
        ["Erhältlich", "nur im Geschäft – kein Versand"],
        ["Laborbericht", "Charge CB-2408-OB"],
      ],
    },
    en: {
      slug: "orange-bud",
      name: "Orange Bud",
      meta: "CBD flowers · 5 g",
      short: "Fruity, sweet orange aroma, THC below 0.3% — available only in store.",
      description: [
        "Orange Bud wins people over with a fruity, sweet scent reminiscent of ripe oranges. According to the lab report for the current batch, CBD content is around 13% and THC below 0.3%.",
        "Like all hemp flowers, Orange Bud is only available in our store at Josefstädter Straße 56 and only for persons aged 18 and over — shipping is not permitted by law.",
      ],
      specs: [
        ["Quantity", "5 g"],
        ["CBD content", "approx. 13% (per lab report)"],
        ["THC content", "below 0.3%"],
        ["Aroma", "Orange, fruity and sweet"],
        ["Availability", "In store only — no shipping"],
        ["Lab report", "Batch CB-2408-OB"],
      ],
    },
  },
  {
    id: "og-kush",
    category: "flowers",
    image: "jar-og-kush",
    tone: "sageStrong",
    price: 32.9,
    shipping: false,
    coa: { batch: "CB-2409-OG", cbd: 13.9, cbg: 0.5, thc: 0.23, tested: "2026-09" },
    de: {
      slug: "og-kush",
      name: "OG Kush",
      meta: "CBD Blüten · 5 g",
      short: "Erdig-würziges Aroma mit einer Note von Kiefer, THC unter 0,3 % – nur im Geschäft.",
      description: [
        "OG Kush ist ein Klassiker mit erdig-würzigem Aroma und einer frischen Note von Kiefer. Die aktuelle Charge enthält laut Laborbericht rund 14 % CBD, der THC-Gehalt liegt unter 0,3 %.",
        "Du bekommst OG Kush ausschließlich in unserem Geschäft in der Josefstädter Straße 56. Hanfblüten unterliegen in Österreich dem Tabakmonopol: kein Versand, Abgabe nur ab 18 Jahren.",
      ],
      specs: [
        ["Inhalt", "5 g"],
        ["CBD-Gehalt", "ca. 14 % (laut Laborbericht)"],
        ["THC-Gehalt", "unter 0,3 %"],
        ["Aroma", "erdig, würzig, Kiefer"],
        ["Erhältlich", "nur im Geschäft – kein Versand"],
        ["Laborbericht", "Charge CB-2409-OG"],
      ],
    },
    en: {
      slug: "og-kush",
      name: "OG Kush",
      meta: "CBD flowers · 5 g",
      short: "Earthy, spicy aroma with a hint of pine, THC below 0.3% — in store only.",
      description: [
        "OG Kush is a classic with an earthy, spicy aroma and a fresh hint of pine. According to the lab report, the current batch contains around 14% CBD with THC below 0.3%.",
        "OG Kush is available exclusively in our store at Josefstädter Straße 56. Hemp flowers are subject to the tobacco monopoly in Austria: no shipping, sale to persons aged 18 and over only.",
      ],
      specs: [
        ["Quantity", "5 g"],
        ["CBD content", "approx. 14% (per lab report)"],
        ["THC content", "below 0.3%"],
        ["Aroma", "Earthy, spicy, pine"],
        ["Availability", "In store only — no shipping"],
        ["Lab report", "Batch CB-2409-OG"],
      ],
    },
  },
  {
    id: "balsam-lavendel",
    category: "cosmetics",
    image: "tin",
    tone: "subtle",
    price: 29.9,
    shipping: true,
    coa: { batch: "CK-2407", cbd: 1.0, thc: 0, tested: "2026-07" },
    de: {
      slug: "cbd-balsam-lavendel",
      name: "CBD Balsam Lavendel",
      meta: "Kosmetik · 50 ml",
      short: "Reichhaltiger Pflegebalsam mit 500 mg CBD, Sheabutter und Lavendelöl für trockene, beanspruchte Haut.",
      description: [
        "Unser CBD Balsam Lavendel pflegt trockene und beanspruchte Hautstellen mit einer reichhaltigen Textur aus Sheabutter, Hanfsamenöl und Bienenwachs. 500 mg CBD und ätherisches Lavendelöl sorgen für ein angenehm beruhigendes Pflegeritual – ideal für Hände, Ellbogen oder Füße.",
        "Einfach eine kleine Menge zwischen den Fingern anwärmen und sanft einmassieren. Nur äußerlich anwenden und nicht auf verletzte Haut auftragen.",
      ],
      specs: [
        ["Inhalt", "50 ml im Aluminiumtiegel"],
        ["CBD-Gehalt", "500 mg"],
        ["Inhaltsstoffe (Auszug)", "Sheabutter, Hanfsamenöl, Bienenwachs, Lavendelöl"],
        ["Anwendung", "äußerlich, auf trockener Haut"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "cbd-balm-lavender",
      name: "CBD Balm Lavender",
      meta: "Cosmetics · 50 ml",
      short: "Rich care balm with 500 mg CBD, shea butter and lavender oil for dry, stressed skin.",
      description: [
        "Our CBD Balm Lavender cares for dry and stressed areas of skin with a rich texture of shea butter, hemp seed oil and beeswax. 500 mg CBD and essential lavender oil make for a pleasantly calming care ritual — ideal for hands, elbows or feet.",
        "Simply warm a small amount between your fingers and massage in gently. For external use only; do not apply to broken skin.",
      ],
      specs: [
        ["Volume", "50 ml aluminium tin"],
        ["CBD content", "500 mg"],
        ["Ingredients (excerpt)", "Shea butter, hemp seed oil, beeswax, lavender oil"],
        ["Use", "External, on dry skin"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
  {
    id: "handcreme",
    category: "cosmetics",
    image: "tin-hand-cream",
    tone: "sage",
    price: 19.9,
    shipping: true,
    coa: { batch: "CK-2408", cbd: 0.27, thc: 0, tested: "2026-08" },
    de: {
      slug: "cbd-handcreme",
      name: "CBD Handcreme",
      meta: "Kosmetik · 75 ml",
      short: "Leichte Handcreme mit 200 mg CBD und Hanfsamenöl – zieht schnell ein, ohne zu fetten.",
      description: [
        "Die CBD Handcreme ist die leichte Begleiterin für jeden Tag: 200 mg CBD und Hanfsamenöl in einer schnell einziehenden Formel, die Hände geschmeidig hält, ohne einen Fettfilm zu hinterlassen.",
        "Perfekt für die Handtasche und für alle, deren Hände durch Kälte, häufiges Waschen oder Arbeit viel aushalten müssen.",
      ],
      specs: [
        ["Inhalt", "75 ml im Tiegel"],
        ["CBD-Gehalt", "200 mg"],
        ["Inhaltsstoffe (Auszug)", "Hanfsamenöl, Glycerin, Sheabutter"],
        ["Anwendung", "äußerlich, mehrmals täglich"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "cbd-hand-cream",
      name: "CBD Hand Cream",
      meta: "Cosmetics · 75 ml",
      short: "Light hand cream with 200 mg CBD and hemp seed oil — absorbs quickly without feeling greasy.",
      description: [
        "The CBD Hand Cream is a light companion for every day: 200 mg CBD and hemp seed oil in a fast-absorbing formula that keeps hands supple without leaving a greasy film.",
        "Perfect for your bag and for anyone whose hands take a lot from cold weather, frequent washing or work.",
      ],
      specs: [
        ["Volume", "75 ml tin"],
        ["CBD content", "200 mg"],
        ["Ingredients (excerpt)", "Hemp seed oil, glycerin, shea butter"],
        ["Use", "External, several times a day"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
  {
    id: "lippenbalsam",
    category: "cosmetics",
    image: "tin-lip-balm",
    tone: "kraft",
    price: 7.9,
    shipping: true,
    de: {
      slug: "cbd-lippenbalsam",
      name: "CBD Lippenbalsam",
      meta: "Kosmetik · 15 ml",
      short: "Lippenpflege in der Dose mit CBD, Bienenwachs und Hanfsamenöl für zarte, geschmeidige Lippen.",
      description: [
        "Der CBD Lippenbalsam schützt und pflegt die Lippen mit Bienenwachs, Hanfsamenöl und CBD. Die kleine Dose passt in jede Jackentasche – besonders praktisch im Wiener Winter.",
      ],
      specs: [
        ["Inhalt", "15 ml Dose"],
        ["CBD-Gehalt", "20 mg"],
        ["Inhaltsstoffe (Auszug)", "Bienenwachs, Hanfsamenöl, Sheabutter"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "cbd-lip-balm",
      name: "CBD Lip Balm",
      meta: "Cosmetics · 15 ml",
      short: "Lip care in a handy tin with CBD, beeswax and hemp seed oil for soft, supple lips.",
      description: [
        "The CBD Lip Balm protects and cares for your lips with beeswax, hemp seed oil and CBD. The small tin fits into any jacket pocket — especially useful during the Viennese winter.",
      ],
      specs: [
        ["Volume", "15 ml tin"],
        ["CBD content", "20 mg"],
        ["Ingredients (excerpt)", "Beeswax, hemp seed oil, shea butter"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
  {
    id: "holz-grinder",
    category: "accessories",
    image: "grinder",
    tone: "sageStrong",
    price: 24.9,
    shipping: true,
    de: {
      slug: "holz-grinder-4-teilig",
      name: "Holz-Grinder 4-teilig",
      meta: "Zubehör · Ø 63 mm",
      short: "Grinder aus Holz mit Mahlwerk aus Metall, Sieb und Pollenfach – Ø 63 mm.",
      description: [
        "Der 4-teilige Holz-Grinder verbindet eine warme Holzoptik mit einem scharfen Mahlwerk aus Metall. Das feine Sieb trennt Pollen ab und sammelt sie im untersten Fach.",
        "Mit 63 mm Durchmesser liegt er gut in der Hand und bietet genug Platz für Kräuter. Der Magnetdeckel hält sicher und lässt sich leicht öffnen.",
      ],
      specs: [
        ["Material", "Holz, Mahlwerk aus Metall"],
        ["Durchmesser", "63 mm"],
        ["Teile", "4 (Mahlwerk, Kammer, Sieb, Pollenfach)"],
        ["Verschluss", "Magnetdeckel"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "wooden-grinder-4-part",
      name: "Wooden Grinder, 4-part",
      meta: "Accessories · Ø 63 mm",
      short: "Wooden grinder with metal teeth, sieve and pollen compartment — Ø 63 mm.",
      description: [
        "The 4-part wooden grinder combines a warm wooden look with sharp metal grinding teeth. The fine sieve separates pollen and collects it in the bottom compartment.",
        "At 63 mm in diameter it sits comfortably in your hand and has plenty of room for herbs. The magnetic lid closes securely and opens easily.",
      ],
      specs: [
        ["Material", "Wood, metal grinding teeth"],
        ["Diameter", "63 mm"],
        ["Parts", "4 (grinder, chamber, sieve, pollen catcher)"],
        ["Closure", "Magnetic lid"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
  {
    id: "metall-grinder",
    category: "accessories",
    image: "grinder-metal",
    tone: "subtle",
    price: 14.9,
    shipping: true,
    de: {
      slug: "metall-grinder-2-teilig",
      name: "Metall-Grinder 2-teilig",
      meta: "Zubehör · Ø 50 mm",
      short: "Kompakter Grinder aus Aluminium mit Magnetdeckel – passt in jede Tasche.",
      description: [
        "Klein, leicht und robust: Der 2-teilige Metall-Grinder aus Aluminium ist ideal für unterwegs. Die scharfen Zähne zerkleinern Kräuter gleichmäßig, der Magnetdeckel hält zuverlässig.",
      ],
      specs: [
        ["Material", "Aluminium"],
        ["Durchmesser", "50 mm"],
        ["Teile", "2"],
        ["Verschluss", "Magnetdeckel"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "metal-grinder-2-part",
      name: "Metal Grinder, 2-part",
      meta: "Accessories · Ø 50 mm",
      short: "Compact 2-part aluminium grinder with sharp teeth and a magnetic lid — fits in any pocket.",
      description: [
        "Small, light and sturdy: the 2-part aluminium grinder is ideal on the go. Its sharp teeth grind herbs evenly and the magnetic lid stays reliably shut.",
      ],
      specs: [
        ["Material", "Aluminium"],
        ["Diameter", "50 mm"],
        ["Parts", "2"],
        ["Closure", "Magnetic lid"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
  {
    id: "uv-glas",
    category: "accessories",
    image: "jar-storage",
    tone: "subtle",
    price: 12.9,
    shipping: true,
    de: {
      slug: "uv-aufbewahrungsglas-100-ml",
      name: "UV-Aufbewahrungsglas 100 ml",
      meta: "Zubehör · 100 ml",
      short: "Violettglas schützt vor Licht – ideal zum Aufbewahren von Kräutern und Blüten.",
      description: [
        "Licht, Luft und Wärme lassen Aromen verfliegen. Das Aufbewahrungsglas aus Violettglas filtert einen Großteil des sichtbaren Lichts, der Schraubdeckel schließt luftdicht ab.",
        "Mit 100 ml Fassungsvermögen ist es groß genug für den Vorrat und klein genug für die Schublade.",
      ],
      specs: [
        ["Material", "Violettglas, Schraubdeckel"],
        ["Inhalt", "100 ml"],
        ["Verschluss", "luftdicht"],
        ["Versand", "in ganz Österreich"],
      ],
    },
    en: {
      slug: "uv-storage-jar-100-ml",
      name: "UV Storage Jar 100 ml",
      meta: "Accessories · 100 ml",
      short: "Violet glass keeps out light — ideal for storing herbs and flowers.",
      description: [
        "Light, air and heat make aromas fade. This violet glass storage jar filters out most visible light, and the screw lid seals airtight.",
        "With 100 ml capacity it’s big enough for your supply and small enough for a drawer.",
      ],
      specs: [
        ["Material", "Violet glass, screw lid"],
        ["Volume", "100 ml"],
        ["Closure", "Airtight"],
        ["Shipping", "Anywhere in Austria"],
      ],
    },
  },
];

/** Products shown in the bestseller section on the home page, in this order. */
export const BESTSELLER_IDS = ["aromaoel-10", "lemon-haze", "balsam-lavendel", "holz-grinder"];

export function getProduct(id: string) {
  const product = PRODUCTS.find((p) => p.id === id);
  if (!product) throw new Error(`Unknown product: ${id}`);
  return product;
}

export function productsIn(category: CategoryKey) {
  return PRODUCTS.filter((p) => p.category === category);
}
