import type { Dict } from "./types";

// Products, prices, counts, opening hours and lab values are placeholders until confirmed by the shop.
export const de: Dict = {
  lang: "de",
  meta: {
    title: "Cannaplace 1080 · CBD Shop in Wien-Josefstadt",
    description:
      "Hochwertige CBD-Blüten, Öle und Kosmetik – laborgeprüft, fair bepreist und persönlich beraten. CBD Shop in der Josefstädter Straße 56, 1080 Wien.",
  },
  announcement: [
    "Laborgeprüfte Qualität",
    "Diskreter Versand in ganz Österreich",
    "Persönliche Beratung im Shop · Josefstädter Str. 56",
  ],
  nav: [
    { label: "Shop", href: "#shop" },
    { label: "CBD Blüten", href: "#sortiment" },
    { label: "CBD Öle", href: "#sortiment" },
    { label: "Kosmetik", href: "#sortiment" },
    { label: "Zubehör", href: "#sortiment" },
    { label: "Ratgeber", href: "#ratgeber" },
    { label: "Über uns", href: "#besuch" },
  ],
  header: {
    search: "Suche",
    account: "Kundenkonto",
    cart: "Warenkorb",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
  },
  hero: {
    eyebrow: "CBD Shop in Wien-Josefstadt",
    titleLine1: "Hanf, wie er",
    titleLine2: "sein sollte.",
    lead: "Hochwertige CBD-Blüten, Öle und Kosmetik – laborgeprüft, fair bepreist und persönlich beraten. Online bestellen oder in der Josefstädter Straße 56 vorbeikommen.",
    ctaPrimary: "Zum Shop",
    ctaSecondary: "Shop besuchen",
    rating: "5,0 · 127 Google-Bewertungen",
    thc: "THC < 0,3 % · laborgeprüft",
    floatLabTitle: "Laborgeprüft",
    floatLabText: "Analysezertifikat zu jedem Produkt",
    floatRatingText: "127 Bewertungen auf Google",
    imageAlt: "CBD Aromaöl und CBD Blüten von Cannaplace",
  },
  valueProps: [
    { icon: "flask", title: "Laborgeprüft", text: "Jede Charge mit Analysezertifikat eines unabhängigen Labors." },
    { icon: "chat", title: "Persönliche Beratung", text: "Im Shop in der Josefstadt oder telefonisch – wir nehmen uns Zeit." },
    { icon: "package", title: "Diskreter Versand", text: "Neutral verpackt und schnell bei dir – in ganz Österreich." },
    { icon: "tag", title: "Faire Preise", text: "Premium-Qualität zu ehrlichen Preisen, direkt vom Fachhändler." },
  ],
  categories: {
    eyebrow: "Sortiment",
    title: "Finde, was zu dir passt",
    link: "Alle Produkte ansehen",
    items: [
      { title: "CBD Blüten", count: "24 Produkte", image: "jar", tone: "kraft" },
      { title: "CBD Öle", count: "12 Produkte", image: "bottle", tone: "sage" },
      { title: "Kosmetik", count: "9 Produkte", image: "tin", tone: "subtle" },
      { title: "Zubehör", count: "18 Produkte", image: "grinder", tone: "sageStrong" },
    ],
  },
  bestsellers: {
    eyebrow: "Beliebt im Shop",
    title: "Unsere Bestseller",
    filters: [
      { key: "all", label: "Alle" },
      { key: "flowers", label: "Blüten" },
      { key: "oils", label: "Öle" },
      { key: "cosmetics", label: "Kosmetik" },
      { key: "accessories", label: "Zubehör" },
    ],
    addToCart: "In den Warenkorb",
    wishlist: "Auf die Merkliste",
    products: [
      {
        id: "aromaoel-10",
        name: "CBD Aromaöl 10 %",
        meta: "CBD Öl · 10 ml",
        price: "€ 39,90",
        rating: "5,0 (48)",
        image: "bottle",
        tone: "sage",
        category: "oils",
        badge: { label: "Bestseller", tone: "dark" },
      },
      {
        id: "lemon-haze",
        name: "Lemon Haze",
        meta: "CBD Blüten · 5 g",
        price: "€ 34,90",
        rating: "4,9 (31)",
        image: "jar",
        tone: "kraft",
        category: "flowers",
        badge: { label: "Neu", tone: "kraft" },
      },
      {
        id: "balsam-lavendel",
        name: "CBD Balsam Lavendel",
        meta: "Kosmetik · 50 ml",
        price: "€ 29,90",
        rating: "4,8 (19)",
        image: "tin",
        tone: "subtle",
        category: "cosmetics",
      },
      {
        id: "holz-grinder",
        name: "Holz-Grinder 4-teilig",
        meta: "Zubehör · Ø 63 mm",
        price: "€ 24,90",
        rating: "5,0 (12)",
        image: "grinder",
        tone: "sageStrong",
        category: "accessories",
      },
    ],
  },
  lab: {
    eyebrow: "Transparenz",
    titleLine1: "Geprüft. Dokumentiert.",
    titleLine2: "Für dich einsehbar.",
    text: "Zu jedem Produkt stellen wir das Analysezertifikat (COA) eines unabhängigen Labors bereit. So siehst du schwarz auf weiß, was drin ist – und was nicht.",
    checklist: [
      "Cannabinoid-Profil mit exaktem CBD-Gehalt",
      "THC unter dem gesetzlichen Grenzwert von 0,3 %",
      "Geprüft auf Pestizide, Schwermetalle und Lösungsmittel",
    ],
    button: "Alle Laborberichte",
    coa: {
      title: "Analysezertifikat",
      subtitle: "CBD Aromaöl 10 % · Charge CP-2410",
      badge: "Geprüft",
      rows: [
        { label: "CBD", value: "10,2 %" },
        { label: "CBG", value: "0,4 %" },
        { label: "THC (Δ9)", value: "0,18 %", note: "unter 0,3 %" },
        { label: "Pestizide", value: "nicht nachweisbar" },
        { label: "Schwermetalle", value: "nicht nachweisbar" },
      ],
      footer: "Unabhängiges Labor · ISO/IEC 17025",
      link: "PDF ansehen",
    },
  },
  store: {
    eyebrow: "Besuch uns",
    title: "Mitten in der Josefstadt",
    text: "Komm vorbei, schnupper rein und lass dich beraten. In unserem Shop findest du das komplette Sortiment – und ehrliche Empfehlungen statt Verkaufsgespräche.",
    hours: "Mo–Fr 10:30–19:00 · Sa 11:00–17:00",
    city: "1080 Wien",
    reviewSummary: "5,0 · 127 Bewertungen auf Google",
    quote: "„Top Auswahl und gute Beratung.“",
    quoteAuthor: "Filippo P. · Google-Bewertung",
    route: "Route planen",
    call: "Anrufen",
    mapAlt: "Karte: Cannaplace in der Josefstädter Straße 56, 1080 Wien",
  },
  journal: {
    eyebrow: "Ratgeber",
    title: "Wissen rund um CBD",
    link: "Alle Artikel",
    readMore: "Weiterlesen",
    articles: [
      { tag: "Grundlagen", time: "5 Min. Lesezeit", title: "Was ist CBD? Die wichtigsten Grundlagen", image: "leaf", tone: "sage" },
      { tag: "Qualität", time: "4 Min. Lesezeit", title: "So liest du ein Analysezertifikat richtig", image: "bottle", tone: "kraft" },
      { tag: "Recht", time: "6 Min. Lesezeit", title: "CBD in Österreich: Was ist erlaubt?", image: "jar", tone: "sageStrong" },
    ],
  },
  newsletter: {
    title: "Neuheiten & Angebote zuerst erfahren",
    text: "Melde dich für unseren Newsletter an – mit Wissen rund um CBD, neuen Sorten und exklusiven Angeboten. Kein Spam, versprochen.",
    placeholder: "Deine E-Mail-Adresse",
    button: "Anmelden",
    note: "Abmeldung jederzeit möglich. Mehr in unserer Datenschutzerklärung.",
    success: "Danke! Die Anmeldung wird in der fertigen Version aktiviert.",
  },
  footer: {
    description:
      "Moderner CBD Shop im 8. Bezirk: hochwertige, legale CBD-Produkte, persönliche Beratung und faire Preise.",
    columns: [
      { title: "Shop", links: ["CBD Blüten", "CBD Öle", "Kosmetik", "Zubehör", "Alle Produkte"] },
      { title: "Service", links: ["Versand & Lieferung", "Rückgabe", "FAQ", "Laborberichte", "Kontakt"] },
      { title: "Rechtliches", links: ["Impressum", "Datenschutz", "AGB", "Widerrufsrecht", "Cookie-Einstellungen"] },
    ],
    contactTitle: "Kontakt",
    hoursShort: "Mo–Fr 10:30–19:00",
    copyright: "© 2026 Cannaplace 1080 CBD Shop. Alle Rechte vorbehalten.",
    legal: "Verkauf nur an Personen ab 18 Jahren · Alle Produkte mit THC < 0,3 % · Keine Arzneimittel",
  },
  cart: { added: "Zum Warenkorb hinzugefügt" },
  ageGate: {
    title: "Bist du 18 Jahre oder älter?",
    text: "Unsere Produkte sind ausschließlich für Erwachsene bestimmt. Bitte bestätige dein Alter, um fortzufahren.",
    yes: "Ja, ich bin 18+",
    no: "Nein",
    denied: "Schade – unsere Seite ist leider nur für Erwachsene zugänglich.",
  },
  fontSwitch: { label: "Schrift", preview: "Vorschau", a: "A · Jost", b: "B · Syne" },
};
