import type { Dict } from "./types";

export const en: Dict = {
  lang: "en",
  meta: {
    title: "Cannaplace 1080 · CBD Shop in Vienna-Josefstadt",
    description:
      "Premium CBD flowers, oils and cosmetics — lab-tested, fairly priced and with personal advice. CBD shop at Josefstädter Straße 56, 1080 Vienna.",
  },
  announcement: [
    "Lab-tested quality",
    "Discreet shipping across Austria",
    "Personal advice in store · Josefstädter Str. 56",
  ],
  nav: [
    { label: "Shop", href: "#shop" },
    { label: "CBD Flowers", href: "#sortiment" },
    { label: "CBD Oils", href: "#sortiment" },
    { label: "Cosmetics", href: "#sortiment" },
    { label: "Accessories", href: "#sortiment" },
    { label: "Guide", href: "#ratgeber" },
    { label: "About us", href: "#besuch" },
  ],
  header: {
    search: "Search",
    account: "Account",
    cart: "Cart",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  hero: {
    eyebrow: "CBD shop in Vienna-Josefstadt",
    titleLine1: "Hemp, the way",
    titleLine2: "it should be.",
    lead: "Premium CBD flowers, oils and cosmetics — lab-tested, fairly priced and with personal advice. Order online or visit us at Josefstädter Straße 56.",
    ctaPrimary: "Shop now",
    ctaSecondary: "Visit the store",
    rating: "5.0 · 127 Google reviews",
    thc: "THC < 0.3% · lab-tested",
    floatLabTitle: "Lab-tested",
    floatLabText: "Certificate of analysis for every product",
    floatRatingText: "127 reviews on Google",
    imageAlt: "Cannaplace CBD aroma oil and CBD flowers",
  },
  valueProps: [
    { icon: "flask", title: "Lab-tested", text: "Every batch comes with a certificate from an independent lab." },
    { icon: "chat", title: "Personal advice", text: "In our Josefstadt store or by phone — we take our time." },
    { icon: "package", title: "Discreet shipping", text: "Neutral packaging, delivered fast — anywhere in Austria." },
    { icon: "tag", title: "Fair prices", text: "Premium quality at honest prices, straight from the specialist." },
  ],
  categories: {
    eyebrow: "Our range",
    title: "Find what suits you",
    link: "View all products",
    items: [
      { title: "CBD Flowers", count: "24 products", image: "jar", tone: "kraft" },
      { title: "CBD Oils", count: "12 products", image: "bottle", tone: "sage" },
      { title: "Cosmetics", count: "9 products", image: "tin", tone: "subtle" },
      { title: "Accessories", count: "18 products", image: "grinder", tone: "sageStrong" },
    ],
  },
  bestsellers: {
    eyebrow: "Popular in store",
    title: "Our bestsellers",
    filters: [
      { key: "all", label: "All" },
      { key: "flowers", label: "Flowers" },
      { key: "oils", label: "Oils" },
      { key: "cosmetics", label: "Cosmetics" },
      { key: "accessories", label: "Accessories" },
    ],
    addToCart: "Add to cart",
    wishlist: "Add to wishlist",
    products: [
      {
        id: "aromaoel-10",
        name: "CBD Aroma Oil 10%",
        meta: "CBD oil · 10 ml",
        price: "€39.90",
        rating: "5.0 (48)",
        image: "bottle",
        tone: "sage",
        category: "oils",
        badge: { label: "Bestseller", tone: "dark" },
      },
      {
        id: "lemon-haze",
        name: "Lemon Haze",
        meta: "CBD flowers · 5 g",
        price: "€34.90",
        rating: "4.9 (31)",
        image: "jar",
        tone: "kraft",
        category: "flowers",
        badge: { label: "New", tone: "kraft" },
      },
      {
        id: "balsam-lavendel",
        name: "CBD Balm Lavender",
        meta: "Cosmetics · 50 ml",
        price: "€29.90",
        rating: "4.8 (19)",
        image: "tin",
        tone: "subtle",
        category: "cosmetics",
      },
      {
        id: "holz-grinder",
        name: "Wooden Grinder, 4-part",
        meta: "Accessories · Ø 63 mm",
        price: "€24.90",
        rating: "5.0 (12)",
        image: "grinder",
        tone: "sageStrong",
        category: "accessories",
      },
    ],
  },
  lab: {
    eyebrow: "Transparency",
    titleLine1: "Tested. Documented.",
    titleLine2: "Open for you to see.",
    text: "For every product we provide the certificate of analysis (COA) from an independent lab — so you can see in black and white what’s inside, and what’s not.",
    checklist: [
      "Cannabinoid profile with exact CBD content",
      "THC below the legal limit of 0.3%",
      "Tested for pesticides, heavy metals and solvents",
    ],
    button: "All lab reports",
    coa: {
      title: "Certificate of analysis",
      subtitle: "CBD Aroma Oil 10% · Batch CP-2410",
      badge: "Passed",
      rows: [
        { label: "CBD", value: "10.2%" },
        { label: "CBG", value: "0.4%" },
        { label: "THC (Δ9)", value: "0.18%", note: "below 0.3%" },
        { label: "Pesticides", value: "not detected" },
        { label: "Heavy metals", value: "not detected" },
      ],
      footer: "Independent lab · ISO/IEC 17025",
      link: "View PDF",
    },
  },
  store: {
    eyebrow: "Visit us",
    title: "In the heart of Josefstadt",
    text: "Drop by, have a look around and get advice. In our store you’ll find the full range — and honest recommendations instead of sales pitches.",
    hours: "Mon–Fri 10:30–19:00 · Sat 11:00–17:00",
    city: "1080 Vienna",
    reviewSummary: "5.0 · 127 reviews on Google",
    quote: "„Top Auswahl und gute Beratung.“",
    quoteAuthor: "Filippo P. · Google review (German)",
    route: "Get directions",
    call: "Call us",
    mapAlt: "Map: Cannaplace at Josefstädter Straße 56, 1080 Vienna",
  },
  journal: {
    eyebrow: "Guide",
    title: "Knowledge about CBD",
    link: "All articles",
    readMore: "Read more",
    articles: [
      { tag: "Basics", time: "5 min read", title: "What is CBD? The essential basics", image: "leaf", tone: "sage" },
      { tag: "Quality", time: "4 min read", title: "How to read a certificate of analysis", image: "bottle", tone: "kraft" },
      { tag: "Law", time: "6 min read", title: "CBD in Austria: what is allowed?", image: "jar", tone: "sageStrong" },
    ],
  },
  newsletter: {
    title: "Be the first to hear about news & offers",
    text: "Sign up for our newsletter — with CBD know-how, new strains and exclusive offers. No spam, promise.",
    placeholder: "Your email address",
    button: "Subscribe",
    note: "Unsubscribe anytime. More in our privacy policy.",
    success: "Thank you! Sign-up will be activated in the final version.",
  },
  footer: {
    description:
      "A modern CBD shop in Vienna’s 8th district: premium, legal CBD products, personal advice and fair prices.",
    columns: [
      { title: "Shop", links: ["CBD Flowers", "CBD Oils", "Cosmetics", "Accessories", "All products"] },
      { title: "Service", links: ["Shipping & delivery", "Returns", "FAQ", "Lab reports", "Contact"] },
      { title: "Legal", links: ["Imprint", "Privacy", "Terms", "Right of withdrawal", "Cookie settings"] },
    ],
    contactTitle: "Contact",
    hoursShort: "Mon–Fri 10:30–19:00",
    copyright: "© 2026 Cannaplace 1080 CBD Shop. All rights reserved.",
    legal: "Sale to persons aged 18+ only · All products with THC < 0.3% · Not a medicinal product",
  },
  cart: { added: "Added to cart" },
  ageGate: {
    title: "Are you 18 or older?",
    text: "Our products are intended for adults only. Please confirm your age to continue.",
    yes: "Yes, I’m 18+",
    no: "No",
    denied: "Sorry — this website is only accessible to adults.",
  },
  fontSwitch: { label: "Font", preview: "Preview", a: "A · Jost", b: "B · Syne" },
};
